<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>ArchitectsPerformanceMod</AssemblyName>
    <Product>Architect's Performance Mod</Product>
    <Version>1.3.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>ArchPerformanceMod</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Test.cs" />

    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <Reference Include="Assembly-CSharp">
      <HintPath>..\lib\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="CoreModule">
      <HintPath>..\lib\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\lib\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineUI">
      <HintPath>..\lib\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="InputSystem">
      <HintPath>..\lib\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEnginePhysics">
      <HintPath>..\lib\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineUIModule">
      <HintPath>..\lib\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineUIElements">
      <HintPath>..\lib\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityLocalization">
      <HintPath>..\lib\Unity.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\lib\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="TextMeshProUGUI">
      <HintPath>..\lib\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineRendering">
      <HintPath>..\lib\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineRenderingHD">
      <HintPath>..\lib\Unity.RenderPipelines.HighDefinition.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineRenderingHDConfig">
      <HintPath>..\lib\Unity.RenderPipelines.HighDefinition.Config.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineVFX">
      <HintPath>..\lib\UnityEngine.VFXModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityCinemachine">
      <HintPath>..\lib\Unity.Cinemachine.dll</HintPath>
    </Reference>
    <Reference Include="UnityTextRendering">
      <HintPath>..\lib\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="FusionRuntime">
      <HintPath>..\lib\Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Crest">
      <HintPath>..\lib\Crest.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>