<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>ArchPerformanceMod</AssemblyName>
    <Product>Architect's Performance Mod</Product>
    <Version>1.4.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>ArchPerformanceMod</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Test.cs" />

    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <Reference Include="Assembly-CSharp">
      <HintPath>..\lib\PUBLIC\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="ArchEmperorLib">
      <HintPath>..\lib\ArchEmperorLib.dll</HintPath>
    </Reference>
    <Reference Include="CoreModule">
      <HintPath>..\lib\PUBLIC\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\lib\PUBLIC\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineUI">
      <HintPath>..\lib\PUBLIC\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="InputSystem">
      <HintPath>..\lib\PUBLIC\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEnginePhysics">
      <HintPath>..\lib\PUBLIC\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineUIModule">
      <HintPath>..\lib\PUBLIC\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineUIElements">
      <HintPath>..\lib\PUBLIC\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityLocalization">
      <HintPath>..\lib\PUBLIC\Unity.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\lib\PUBLIC\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="TextMeshProUGUI">
      <HintPath>..\lib\PUBLIC\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineRendering">
      <HintPath>..\lib\PUBLIC\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineRenderingHD">
      <HintPath>..\lib\PUBLIC\Unity.RenderPipelines.HighDefinition.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineRenderingHDConfig">
      <HintPath>..\lib\PUBLIC\Unity.RenderPipelines.HighDefinition.Config.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineVFX">
      <HintPath>..\lib\PUBLIC\UnityEngine.VFXModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityCinemachine">
      <HintPath>..\lib\PUBLIC\Unity.Cinemachine.dll</HintPath>
    </Reference>
    <Reference Include="UnityTextRendering">
      <HintPath>..\lib\PUBLIC\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <!-- <Reference Include="FusionRuntime">
      <HintPath>..\lib\PUBLIC\Fusion.Runtime.dll</HintPath>
    </Reference> -->
    <Reference Include="UniverseLib">
      <HintPath>..\lib\UniverseLib.BIE.IL2CPP.Interop.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>